const Home = () => {
    return (
        <>
            <div className="home-top-container">
                Sample Text
            </div>
            <div className="home-text">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae quo inventore, soluta laudantium facilis eligendi enim quasi accusantium ad eius magni quibusdam quos placeat deserunt reprehenderit explicabo, obcaecati dolore nobis aut tenetur libero ab nam, blanditiis odit. Provident facilis reprehenderit quis commodi voluptas quasi, assumenda error voluptates quo expedita numquam nulla quam nemo ab laboriosam cum dolorum, eveniet asperiores, magni accusamus quod? Porro pariatur eius totam voluptate reiciendis beatae eveniet ab facilis labore id, perspiciatis nisi aut ut exercitationem. Labore modi vel accusamus dolor odio. Tenetur officiis quae animi, provident eum nihil iste aut quos nemo sapiente. Necessitatibus, nisi ab?</p>
           </div>
        </>
    )
}
export default Home;